const informal_slogans = [
    "Because Memory Leaks Aren't Just for Code! 🧠💀",
    "Docs? Nah, These Are My Survival Notes 🛠️📝",
    "Code, Coffee, Chaos. ☕💻",
    "If it's not in my notes, it doesn't exist. 📝🚀",
    "AI is cool, but have you tried debugging? 🤖🔥",
    "Because Stack Overflow won’t always save you. 🛟",
    "Full-Stack? More like Full-Stress. 😵‍💻",
    "Data Science: Turning coffee into insights. ☕📊",
    "Commit your notes before your brain crashes. 💾🧠",
    "99 problems, but a bug ain't one... oh wait. 🐞😵",
    "My brain = RAM, these notes = SSD. ⚡",
    "Tech moves fast, my notes move faster. 🚀📚",
    "AI will replace jobs, but not my note-taking. 🤓",
    "Ctrl + S before it's too late. 💾🔥",
    "Debugging is like being a detective in your own crime scene. 🕵️‍♂️🐛",
    "Where ‘Hello World’ meets deep learning. 🌍🤖",
    "This is where semicolons go to retire. ;)",
    "Code it. Break it. Fix it. Document it (maybe). 📜",
    "If (lost) { check notes(); } 🔍",
    "Machine Learning? More like Guesswork++. 🤔📈",
    "Building apps, breaking servers. 🛠️🔥",
    "I teach AI, yet my printer still won’t listen. 🤖🖨️",
    "Error 404: Motivation Not Found. ❌",
    "Because ‘just Google it’ isn’t always enough. 🔍",
    "When in doubt, console.log(‘check notes’); 📜",
    "Backend, frontend, mental breakdown-end. 💥",
    "Trust me, I'm a software engineer. 😏",
    "Notes: The real cloud storage. ☁️📚",
    "Data Science: The art of making spreadsheets sound cool. 📊🎩",
    "First, we train AI. Then, AI trains us. 🤖💡",
    "Deploying notes… please don’t crash. 🚀💀",
    "Everything is a database if you believe hard enough. 🗃️",
    "There’s an API for that... probably. 🌐",
    "Write code, not excuses. 💻📝",
    "One does not simply write clean code. 😆",
    "My AI can predict the future, but not my next error. 🛠️",
    "Documentation: The final boss of software development. 📖💀",
    "Coding is like magic, except when it’s debugging. 🎩🐞",
    "I write notes so Future Me won’t hate Past Me. ⏳",
    "Where dreams are coded and APIs are broken. 🧑‍💻",
    "AI: Making humans obsolete, one line at a time. 🤖💥",
    "May your commits be bug-free and your models be accurate. 🙏",
    "Emerging Tech: Fancy words for ‘not quite working yet’. 🤯",
    "Full-Stack Developer: Because one headache wasn't enough. 😵",
    "Data never lies, but it sure misleads. 📊🤡",
    "Logging my genius before I forget. 🔍📝",
    "Notes now, world domination later. 🌍🚀",
    "Syntax errors? Just another Tuesday. 🔥💻",
    "Tech evolves, my notes keep up. 📚⚡",
    "The only server I trust is in my notes. 🖥️",
    "Cloud computing? My notes were in the cloud first. ☁️",
    "Code runs, data flows, notes grow. 🌊",
    "Where bugs go to get documented. 🐛📖",
    "Read, code, debug, repeat. 🔄",
    "Learning one line at a time. 📜",
    "Git good or git lost. 🚀",
    "AI isn't scary... yet. 😬",
    "If AI takes over, at least I wrote the notes. 📝🤖",
    "Git commit, push, pray. 🙏💻",
    "Future Me will thank me for these notes. 📝⌛",
    "Because Google won’t always be there for you. 🔍😢",
    "Data Science: Where statistics meets sorcery. 🔮📊",
    "If (struggle) { checkNotes(); } 🛠️",
    "I break things so you don’t have to. 🛠️🔥",
    "Full-Stack: Jack of all trades, debugger of none. 😵‍💻",
    "Notes: Because my brain is just RAM with bad garbage collection. 🧠💾",
    "AI may take over, but my notes will survive. 🤖📚",
    "Running on coffee and API errors. ☕💥",
    "Where ‘Hello World’ meets deep learning. 🌍🤖",
    "One does not simply deploy on Friday. ⚠️",
    "Keeping track of errors so I don’t make them twice. 📝🐞",
    "Machine Learning? More like Machine Guessing. 🤔📈",
    "Debugging my code and my life. 🔍💀",
    "Writing notes like it's production-ready. 📝🚀",
    "Data never lies… except when it does. 📊🤡",
    "A place where semicolons go to die. ;)",
    "Ctrl + S is my superpower. 💾🦸‍♂️",
    "Backend, frontend… when does it end? 😵",
    "Full-Stack: Because single problems weren’t enough. 🛠️🔥",
    "Data Science is 90% cleaning, 10% panic. 📊😰",
    "There’s no place like 127.0.0.1 🏡",
    "Deploying notes… hoping for no merge conflicts. 🚀⚠️",
    "I make mistakes, but at least I document them. 📖😂",
    "If my AI model fails, I’ll just blame the data. 🤖🤷",
    "Debugging: Turning coffee into errors since forever. ☕🐞",
    "Notes are the only database I can trust. 💾",
    "Coding is just Google, copy, paste, debug. 🔄💻",
    "AI is cool, but have you ever fixed a CSS bug? 🎨💀",
    "Writing notes like a dev writes tests—almost never. 📜",
    "Because remembering is overrated. 🧠🚫",
    "Logging my thoughts so I don’t have to think. 📝💭",
    "Full-Stack: The art of suffering in both frontend and backend. 😭",
    "Deploying notes, please don’t crash. 🚀💀",
    "Emerging Tech: Just fancy words for ‘not stable yet’. 🤯",
    "99 problems, and JavaScript is most of them. ⚡",
    "AI won't take over if I keep writing bad code. 🤖💀",
    "Sometimes I write notes, sometimes I just panic. 😅",
    "Welcome to the cloud… where my thoughts live now. ☁️",
    "Trying to keep up with tech, failing gracefully. 🚀",
    "Tech evolves, my notes adapt. 📚⚡",
    "The only logs I read are my debugging logs. 🔍",
    "If it works, it’s not a bug—it’s a feature. 🚀",
    "Because I can’t afford to forget. 📝💸",
    "AI can predict trends, but not my coding errors. 🤖💥",
    "Trust me, I'm a developer. 🛠️😏",
    "Learning never stops, debugging neither. 🔄🐛",
    "Data speaks. My notes listen. 📊👂",
    "These notes are version-controlled… unlike my life. 🔀",
    "Coding is an art. Debugging is the reality check. 🎭",
    "AI is great, but it still can’t fix my bugs. 🤖🐛",
    "Writing notes so I can debug my brain later. 📝🧠",
    "Data-driven, coffee-fueled, sleep-deprived. ☕📊😴",
    "Backend, frontend, debug-end. 😵‍💻",
    "If my AI model fails, it’s a ‘feature,’ not a bug. 🤖",
    "Notes: The only documentation I actually read. 📖",
    "I only deploy on Fridays for the adrenaline rush. 🚀🔥",
    "Machine Learning? More like Machine Guessing. 📊🤷",
    "When in doubt, blame the caching. 🔄",
    "AI may take over the world, but not my notes. 🤖📝",
    "Debugging: Turning mistakes into learning moments. 🐞✨",
    "One tab for work, fifty for Stack Overflow. 🔥",
    "When all else fails, restart the server. 🔄🖥️",
    "My code runs on hopes and dreams. 💻💭",
    "Full-Stack dev: Too much work, not enough time. ⏳",
    "Data science: Making predictions, missing deadlines. 📊⏳",
    "Bug-free code? I don’t believe in fairy tales. 🧚‍♂️🐛",
    "AI learns, but I forget. 🤖🧠",
    "I write notes so I don’t have to think too hard. 🤯",
    "Every commit is a prayer to the coding gods. 🙏💾",
    "Where semicolons go missing. ;🚀",
    "I don’t always test my code, but when I do, it’s in production. 🔥",
    "Coding is easy. Debugging is an extreme sport. 🏅",
    "Trying to keep up with tech, failing gracefully. 🚀📉",
    "AI isn’t perfect, but neither am I. 🤖🤷‍♂️",
    "My browser history is 90% 'How to fix...'. 🔍",
    "Life’s too short for slow queries. 🚀🔍",
    "I break code for a living. 🛠️🔥",
    "My notes: Because Google won’t always be there. 🔍📚",
    "Learning today so I can forget tomorrow. 📝😆",
    "Cloud computing? My brain has been in the cloud for years. ☁️",
    "Where ‘Hello World’ meets deep learning. 🌍🤖",
    "Every problem is a database problem. 🗃️",
    "AI won’t replace me… yet. 😬",
    "Just another day of making software worse before making it better. 🔄",
    "You don’t need AI to predict I’ll need coffee. ☕",
    "Tech evolves, my notes try to keep up. 📚",
    "Notes: My personal Stack Overflow. 📝🔥",
    "Deploying notes… hoping for no merge conflicts. 🚀⚠️",
    "Full-Stack? More like Full-Stress. 😵‍💻",
    "Training AI, but my code still won’t listen. 🤖🖥️",
    "Tech moves fast, my memory doesn’t. 🧠💾",
    "If (stuck) { read_notes(); } 📝🔍",
    "AI can predict trends, but not my next error. 🤖💥",
    "Debugging is like being a detective in your own crime scene. 🔍🐛",
    "Future Me will be grateful for these notes. ⏳📝",
    "Documentation: The final boss of software development. 📜",
    "Machine learning: Fancy math with extra confusion. 🤯",
    "Every AI model I train is just slightly more confused than me. 🤖💭",
    "I don’t trust AI… yet. 😆",
    "Every API request is a cry for help. 🌐😢",
    "My notes: Because memory leaks aren’t just for code. 🧠💀",
    "Machine Learning is just statistics in disguise. 🎭📊",
    "Writing code is hard. Writing documentation is impossible. 😭",
    "I talk to my AI models. They don’t respond… yet. 🤖",
    "All I wanted was a simple project. Now I have 10 services running. 😵",
    "Cloud is just someone else’s computer. ☁️🖥️",
    "Working in tech means fixing the printer too. 🖨️🤦‍♂️",
    "If it's not in my notes, it doesn’t exist. 📝🚀",
    "I fix one bug, create five more. 🔄🐛",
    "Coding is like playing with fire—exciting and dangerous. 🔥",
    "First, we train AI. Then, AI trains us. 🤖",
    "The only logs I read are my debugging logs. 🔥📜",
    "I don’t code—I just argue with the compiler. 🤖💢",
    "Notes: The only thing between me and total confusion. 🤯",
    "I have a love-hate relationship with semicolons. ;🤬",
    "Write, test, fail, repeat. 🔄",
    "I teach AI, yet my smart speaker never listens. 🤖🔊",
    "Merge conflict: The reason I cry at night. 😭",
    "I make software. Sometimes, it even works. 💻",
    "One tab for work, twenty for debugging. 🤯",
    "Predicting the future… except for my deadlines. 📆📊",
    "You never forget a memory leak. 🧠💀",
    "Notes: My way of outsourcing my memory. 🔍📚",
    "My AI is learning, but I’m still debugging. 🤖🛠️",
    "Deploying AI… let’s hope it doesn’t go Skynet. 🤖💀",
    "Tech changes fast, but my debugging skills stay the same. 🛠️",
    "I keep notes because AI doesn’t read my mind yet. 📝🤖",
    "If my code runs, I get suspicious. 🤔",
    "Write code, break things, fix later. 🔄",
    "Notes are my personal cheatsheet for life. 📖",
    "Where ‘working fine’ means ‘I’m scared to touch it.’ 😆",
    "One does not simply write clean code. 😂",
    "Emerging Tech: Just fancy words for ‘not stable yet’. 🤯",
    "If AI takes over, I hope it reads my notes first. 🤖📝",
    "Programming: Because ‘just Google it’ isn’t always enough. 🔍",
    "Every AI model I make is just a fancier coin flip. 🤖🪙",
    "Syntax errors? Just another Tuesday. 🔥",
    "Data is power. My notes are the backup. ⚡",
    "The cloud remembers what I forget. ☁️",
    "If debugging is removing bugs, then programming must be adding them. 🐛",
    "Machine Learning: The science of making bad predictions faster. 🚀",
    "Coding is an art. Debugging is the reality check. 🎭",
    "These notes are version-controlled… unlike my life. 🔀",
    "Data never lies, but it sure misleads. 📊🤡",
    "If I had a dollar for every bug, I’d be rich. 💰🐛",
    "Every problem is a feature waiting to happen. 🚀",
    "Future AI will laugh at my code. 🤖😂",
    "This note-taking app is my backup brain. 🧠💾",
    "Code like it’s production, debug like it’s practice. 🚀🐞",
    "My notes are 90% reminders, 10% regrets. 📖😂",
    "Turning coffee into code and code into bugs. ☕💻🐛",
    "Stack Overflow is my co-pilot. 🛩️📚",
    "AI is cool, but have you ever fixed a merge conflict? 🤖🔥",
    "If it's not documented, did it really happen? 📝🤷‍♂️",
    "Full-Stack: Where backend and frontend blame each other. 🎭",
    "Data Science: Where math meets marketing. 📊🎯",
    "I train AI, but my autocorrect still betrays me. 🤖📱",
    "AI can predict the future, but not my debugging struggles. 🤯",
    "I commit code like I commit to gym memberships… rarely. 😆",
    "The only bug-free software is the one you haven't tested. 🔥",
    "Notes today, world domination tomorrow. 🌍🚀",
    "Cloud computing: My data’s floating, my patience is sinking. ☁️⚓",
    "My best debugging tool is taking a nap. 😴💡",
    "I write code. Sometimes, it even works. 🤷‍♂️",
    "99% coding, 1% fixing typos. 🔍",
    "Machine learning? More like machine guessing. 🎲",
    "Programming is like magic… until you see the error logs. 🧙‍♂️",
    "AI can beat humans at chess, but still can't center a div. ♟️📐",
    "I don’t need a therapist, I have `console.log()`. 🛠️",
    "My code has too many bugs to be Open Source. 🐛😂",
    "Tech debt is just future me’s problem. ⏳💳",
    "My documentation is just an email thread. 📧💀",
    "I make software worse before making it better. 🔄",
    "There’s an API for that… probably. 🌐",
    "Backend is where the magic happens… and the database cries. 🛠️💾",
    "Notes: My personal Stack Overflow. 📝🔥",
    "Full-Stack: Master of all, expert in none. 😵‍💻",
    "Data Science: Finding patterns in chaos. 📊🌀",
    "AI: Automating mistakes since forever. 🤖🚧",
    "I deploy code just to see what happens. 🚀💥",
    "Every commit is a prayer to the coding gods. 🙏💾",
    "CSS is just witchcraft for web developers. 🎨🧙",
    "Programming is 10% writing code, 90% staring at it. 👀",
    "If it works, I don’t ask why. 🤷‍♂️",
    "AI can drive cars but still fails at CAPTCHAs. 🚗🤖",
    "The real cloud storage is my collection of sticky notes. ☁️📜",
    "Code so clean, even AI is impressed. 🤖✨",
    "Every AI model I train is slightly more confused than I am. 😵‍💫",
    "I don’t always test my code, but when I do, it’s in production. 🔥",
    "Git push first, ask questions later. 🚀",
    "The only thing scalable in my app is my stress. 📈😵",
    "Software development: From confusion to catastrophe. 🔄",
    "One does not simply deploy on a Friday. 😅",
    "Frontend dev: Where everything looks good but nothing works. 🎨💥",
    "Debugging: Because I wrote this mess. 🛠️",
    "Tech changes, my imposter syndrome stays the same. 😬",
    "Programming: 50% fixing bugs, 50% creating them. 🐞",
    "AI won’t replace me, but it will judge my code. 🤖😆",
    "AI can read medical scans but still can’t beat me at tic-tac-toe. 🤖🎮",
    "Deploying AI… please don’t become sentient. 🤖💀",
    "Code now, refactor never. 💀",
    "The most used programming language? Copy-Paste. 📋💻",
    "Data Science: Fancy word for 'spreadsheet magic'. 📊✨",
    "CSS: Where margin 0 auto sometimes works, sometimes doesn’t. 🤷‍♂️",
    "Error 404: Motivation not found. ❌",
    "Code quality is directly proportional to caffeine intake. ☕📈",
    "A good developer knows when to restart their laptop. 🔄",
    "Frontend? Backend? I’m just trying to make it work. 😵‍💻",
    "Building AI to replace myself… slowly. 🤖",
    "If `true`, then panic. 😨",
    "AI may automate jobs, but it can’t fix my commit history. 🔥",
    "Half my job is naming variables correctly. 🤯",
    "My documentation is just a series of TODOs. 📝",
    "If code works, don’t touch it. 🚧",
    "My AI can predict stock prices, but not my deadlines. 📈⏳",
    "Notes: Because memory leaks aren’t just for code. 🧠💀",
    "Backend dev: Where logs tell half the story. 📜",
    "AI: The best excuse for bad predictions. 📊",
    "Debugging: Finding out what you thought your code did. 🧐",
    "I don’t always comment my code, but when I do, it’s sarcastic. 😆",
    "AI can analyze sentiment, but it doesn’t understand my pain. 😭",
    "The fastest code is code that doesn’t exist. 🏃‍♂️",
    "Cloud computing? My files were in the cloud first. ☁️📝",
    "If my AI model works, I get suspicious. 🤨",
    "Documentation is just a wish list of features. 📜",
    "If it's stupid but it works, it’s not stupid. 🤷‍♂️",
    "AI is just a really fancy `if-else` statement. 🤖",
    "Programmers: Writing automation so they can work more. 🔄",
    "DevOps: Because everyone deserves downtime. 🛠️💤",
    "I write bugs for a living. 🐛💻",
    "Backend dev: Where things make sense until they don’t. 🔥",
    "My AI model is 95% accurate… at being wrong. 😆",
    "I don’t refactor. I just rewrite. 💀",
    "Git commit messages should be an art form. 🎨",
    "Error logs are just cryptic love letters from my code. 💌",
    "There’s an API for that… but good luck finding the docs. 😆",
    "Machine learning is just statistics in a leather jacket. 📊😎",
    "Every AI model is just a fancy way of flipping a coin. 🤖🪙",
    "Deploying AI: Because my instincts are usually wrong. 🤯",
    "Frontend dev: Where JavaScript works… until it doesn’t. 🛠️",
    "The cloud is just someone else’s computer, and I’m paying for it. ☁️💸",
    "My AI model can write poetry, but still can’t pass my unit tests. 🤖📜",
    "Data science: Automating Excel one step at a time. 📊🔥",
    "Tech debt? More like tech bankruptcy. 💳💀",
    "My coding process: Write, test, cry, repeat. 😭",
    "My AI is learning faster than I am. 😵‍💫",
    "I trust my AI model about as much as I trust my umbrella in a storm. ☔",
    "Debugging: Because I didn't plan ahead. 🛠️😅",
    "AI-generated text: Still not as weird as my comments. 🤖📝",
    "Tech evolves, my frustration remains the same. 😆",
    "If AI takes over, at least I documented my notes. 🤖📚"
];


export default informal_slogans;